### ISSUE TITLE
Fix crashing bug

### ISSUE THREAD

**Issue by ste616** [ste616/atca-rapid-response-api#1]
I think, because the JSON request had just been renamed, due to the source setting, the code got confused and crashed. Error message follows:

`Checking...

starting to run!

Traceback (most recent call last):

  File "rapid_response_actioner.py", line 1017, in <module>
    atca, sched, logFile)

  File "rapid_response_actioner.py", line 301, in checkOverride
    monica.updatePoints()

  File "/n/ste616/usr/src/atca-rapid-response/webserver/env/lib/python2.7/site-packages/cabb_scheduler/monica_information.py", line 107, in updatePoints

    response = self.__comms(data)

  File "/n/ste616/usr/src/atca-rapid-response/webserver/env/lib/python2.7/site-packages/cabb_scheduler/monica_information.py", line 101, in __comms

    return json.loads(postResponse.text)

  File "/usr/lib/python2.7/json/__init__.py", line 326, in loads
    return _default_decoder.decode(s)

  File "/usr/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

  File "/usr/lib/python2.7/json/decoder.py", line 383, in raw_decode
    raise ValueError("No JSON object could be decoded")

ValueError: No JSON object could be decoded
`

**Comment by ste616** [comment]
Scratch that, it actually looks like the fault is in the MoniCA subsystem.

**Comment by ste616** [comment]
Ooops, wrong repository, this should have gone into the main actioner repository!
